### (list all Students)
GET http://localhost:8080/api/students
Accept: application/json

### (list all Students by prefix)
GET http://localhost:8080/api/students?prefix=kiss
Accept: application/json

### (find Student by id)
GET http://localhost:8080/api/students/2
Accept: application/json

### (create Student)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@gmail.com",
  "gitHub": "kissj"
}

### (update Student)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@yahoo.com",
  "gitHub": "kissj",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### (delete Student)
DELETE http://localhost:8080/api/students/3

### Validation (elvárt válasz: a validáció miatt elbukik a Student létrehozása)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": null,
  "email": "kissj@gmail.com",
  "gitHub": "kissj"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student létrehozása)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "   ",
  "email": "kissj@gmail.com",
  "gitHub": "kissj"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student létrehozása)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": null,
  "gitHub": "kissj"
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student létrehozása)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "  ",
  "gitHub": "kissj"
}

### Validation (elvárt válasz: létrejön a Student)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@gmail.com",
  "gitHub": null
}

### Validation (elvárt válasz: létrejön a Student)
POST http://localhost:8080/api/students
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@gmail.com",
  "gitHub": "  "
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student módosítása)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": null,
  "email": "kissj@yahoo.com",
  "gitHub": "kissj",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student módosítása)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "  ",
  "email": "kissj@yahoo.com",
  "gitHub": "kissj",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student módosítása)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": null,
  "gitHub": "kissj",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a validáció miatt elbukik a Student módosítása)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "  ",
  "gitHub": "kissj",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a Student adatai módosulnak)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@yahoo.com",
  "gitHub": null,
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a Student adatai módosulnak)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@yahoo.com",
  "gitHub": "   ",
  "comment": "Rendesen halad az ütemezett anyaggal."
}

### Validation (elvárt válasz: a Student adatai módosulnak)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@yahoo.com",
  "gitHub": "kissj",
  "comment": null
}

### Validation (elvárt válasz: a Student adatai módosulnak)
PUT http://localhost:8080/api/students/3
Content-Type: application/json
Accept: application/json

{
  "name": "Kiss József",
  "email": "kissj@yahoo.com",
  "gitHub": "kissj",
  "comment": "   "
}