### (list all TrainingClasses)
GET http://localhost:8080/api/trainingclasses
Accept: application/json

### (find TrainingClass by id)
GET http://localhost:8080/api/trainingclasses/2
Accept: application/json

### (create TrainingClass)
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "name": "Struktúraváltó haladó",
  "startDate": "2021-06-07"
}

### (update TrainingClass)
PUT http://localhost:8080/api/trainingclasses/3
Content-Type: application/json
Accept: application/json

{
  "name": "Struktúraváltó haladó Java",
  "dates": {
    "startDate": "2021-06-07",
    "endDate": "2021-08-09"
  }
}

### (delete TrainingClass)
DELETE http://localhost:8080/api/trainingclasses/2

### (add Syllabus)
PUT http://localhost:8080/api/trainingclasses/4/syllabuses
Content-Type: application/json
Accept: application/json

{
  "syllabusId": 3
}

### Validation (elvárt válasz: a validáció miatt elbukik a TrainingClass létrehozása)
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "name": null,
  "startDate": "2021-06-07"
}

### Validation (elvárt válasz: a validáció miatt elbukik a TrainingClass létrehozása)
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "name": "  ",
  "startDate": "2021-06-07"
}

### Validation (elvárt válasz: létrejön a TrainingClass)
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "name": "Struktúraváltó haladó",
  "startDate": null
}

### Validation (elvárt válasz: létrejön a TrainingClass)
POST http://localhost:8080/api/trainingclasses
Content-Type: application/json
Accept: application/json

{
  "name": "Struktúraváltó haladó",
  "startDate": ""
}

### Validation (elvárt válasz: a validáció miatt elbukik a TrainingClass módosítása)
PUT http://localhost:8080/api/trainingclasses/3
Content-Type: application/json
Accept: application/json

{
  "name": "Struktúraváltó haladó Java",
  "dates": {
    "startDate" : "2021-08-09",
    "endDate": "2021-06-07"
  }
}

### Validation (elvárt válasz: a validáció miatt elbukik a Syllabus hozzárendelése a TrainingClasshoz)
PUT http://localhost:8080/api/trainingclasses/4/syllabuses
Content-Type: application/json
Accept: application/json

{
  "syllabusId": null
}